name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build
        run: |
          npm install
          npm run build
      - name: Lighthouse
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --config .github/workflows/lighthouse.json